# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
variables:
  CI_DEBUG_TRACE: 'true'
stages:
- release
- test
- deploy
pages:
  image: node:18.17.1
  before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  script:
  - pnpm install
  - pnpm build
  - mv dist public
  cache:
    key:
      files:
      - pnpm-lock.yaml
    paths:
    - ".pnpm-store"
  artifacts:
    paths:
    - public
  rules:
  - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
sast:
  stage: test
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
