# The Docker image that will be used to build your app

stages:
  - release

image: node:18.17.1
# Functions that should be executed before the build script is run
before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store

release-image:
  stage: release
  extends: .release-image

pages:
  stage: release
  script:
    - pnpm install
    - pnpm build
    - mv dist public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

include:
  - project: template/gitlabci-template
    file: docker.gitlab-ci.yml