// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/paragraph/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/settings" | "/paragraph/:id";
  };
  "./layouts/Main.layout.tsx": {
    id: "layouts/Main.layout";
    page: "/" | "/settings" | "/paragraph/:id";
  };
  "./pages/Search.page.tsx": {
    id: "pages/Search.page";
    page: "/";
  };
  "./pages/Settings.page.tsx": {
    id: "pages/Settings.page";
    page: "/settings";
  };
  "./pages/Paragraph.page.tsx": {
    id: "pages/Paragraph.page";
    page: "/paragraph/:id";
  };
};